### ISSUE TITLE
error 1 and error 2 after running config - please advise

### ISSUE THREAD

**Issue by sndik16** [vtjnash/atlas-3.10.0#4]
Hello,

I am using Mac (el capitan 10.11.6)  and I am trying to install ATLAS on my computer using the command line.
I am very new to the computer world, so thank you for your patience.

When I input into the Terminal command line the following command
../configure -b 32 --with-netlib-lapack-tarfile=/Users/marialaptop2/lapack-3.4.1.tgz

I get some errors

make[2]: *** [leafstart] Error 1
make[1]: *** [startup] Error 2
make: *** [startup] Error 2
mv: rename lapack-3.4.1 to ../reference/lapack-3.4.1: Directory not empty
DONE configure
Marias-MacBook-Pro:atlas_build_dir marialaptop2$ 

I execute this command while in marialaptop2/ATLAS3.10.3/atlas_build_dir/ folder
and my lapack-3.4.1.tgz file is in /Users/marialaptop2/lapack-3.4.1.tgz folder

_I need to get ATLAS in order to be able to install another program, SEXTRACTOR, because when I install SEXTRACTOR, I get the following error "CBLAS/LAPack include files not found! Exiting."._

thank you very much,
Maria

**Comment by vtjnash** [comment]
This is an old fork of atlas modified to build on ~~mays~~ msys. Google should be able to help you find the actual atlas project sources on sourceforge.
